TEP-Final/todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from todo_lists import views

urlpatterns = [
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
    path('todo_lists/', include('todo_lists.urls')),
    #path('users/', include('users.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    
]

TEP-Final/todo_lists/urls.py
# sub urls for todo_list


from django.urls import path

from . import views

app_name = 'todo_lists'
urlpatterns = [
    # homepage
    path('', views.projects, name='index'),
    # page that shows all projects
    path('projects/', views.projects, name='projects'),
    # details of a project
    path('projects/<int:project_id>/', views.project, name='project'),
    path('visual/<int:project_id>/', views.visualisation, name='visualisation'),
    # add a new project
    path('new_project/', views.new_project, name='new_project'),
    path('todoprogress/<slug:pk>/', views.progress, name='todoprogress'),
    path('teams/', views.teams, name='teams'),
    path('teams/<int:team_id>/', views.team, name='team'),


    # for creating new todo tasks by user
    path('new_todo/<int:project_id>/', views.new_todo, name='new_todo'),
    # for creating new todo tasks by user
    path('new_progress/<int:project_id>/', views.add_to_progress, name='new_progress'),
    # for creating new todo tasks by user
    path('new_done/<int:project_id>/', views.add_to_done, name='new_done'),
    
    # for editing current todo tasks
    path('edit_todo/<int:todo_id>/', views.edit_todo, name='edit_todo'),
    # for editing current in-progress tasks
    path('edit_progress/<int:progress_id>/', views.edit_progress, name='edit_progress'),
    path('progress/', views.visualisation, name='visualisation'),
    path('delete/<str:todo_id>/', views.delete_todo, name='delete_todo'),
    path('delete_project/<str:project_id>/', views.delete_project, name='delete_project'),
    path('edit_project/<str:project_id>/', views.edit_project, name='edit_project'),

    path('wiki', views.wikiMain, name='wikiMain'),
    path('wiki1', views.wiki1, name='wiki1'),
    path('readwiki1', views.readwiki1, name='readwiki1'),
    path('wiki2', views.wiki2, name='todo_lists_wiki2'),
    path('readwiki2', views.readwiki2, name='readwiki2'),
    path('wiki3', views.wiki3, name='wiki3'),
    path('readwiki3', views.readwiki3, name='readwiki3'),
    path('wiki4', views.wiki4, name='wiki4'),
    path('readwiki4', views.readwiki4, name='readwiki4'),
    path('wiki5', views.wiki5, name='wiki5'),
    path('readwiki5', views.readwiki5, name='readwiki5'),
    path('wiki6', views.wiki6, name='wiki6'),
    path('readwiki6', views.readwiki6, name='readwiki6'),
    path('wiki7', views.wiki7, name='wiki7'),
    path('readwiki7', views.readwiki7, name='readwiki7'),
    path('wiki8', views.wiki8, name='wiki8'),
    path('readwiki8', views.readwiki8, name='readwiki8'),



    path('resourcepage', views.resourcepage, name='resourcepage'),
    path('resource1', views.resource1, name='resource1'),
    path('readresource1', views.readresource1, name='readresource1'),
    path('resource2', views.resource2, name='resource2'),
    path('readresource2', views.readresource2, name='readresource2'),
    path('resource3', views.resource3, name='resource3'),
    path('readresource3', views.readresource3, name='readresource3'),
    path('resource4', views.resource4, name='resource4'),
    path('readresource4', views.readresource4, name='readresource4'),
    path('upload', views.upload, name='upload'),
    path('checkresource<id>', views.checkresource, name='checkresource'),
    path('downloadresource<id>', views.downloadresource, name='downloadresource'),
    path('searchref', views.searchref, name='searchref'),

    path('searchref', views.searchref, name='searchref'),
    path('assignpage/', views.assign, name='assign'),
    path('assign2', views.assign2, name='project_assign2'),
]

TEP-Final/user/urls.py
# users urls
from django.urls import path, include
from user.views import index
urlpatterns = [
    path('', index.index, name='index'),
    path('login/', index.login, name='login'),
    path('register/', index.register, name='register'),
    path('logout/', index.logout, name='logout'),
]

TEP-Final/todo_lists/forms.py
from django import forms

from .models import Project, Todo, Progress, Done, Team


# user can type in project now
class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['member', 'name', 'due_date', 'project_code', 'details']
        widgets = {
                    'start_date': forms.SelectDateWidget(),
                    'due_date': forms.SelectDateWidget(),
                    
        }


# user can type in to do tasks now
class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['project', 'team', 'name', 'start_date', 'due_date', 
                  'project_code', 'details','priority_level']
        # labels = {'project': '', 'create_date': ''}
        widgets = {
                    # 'project': forms.Textarea(attrs={'col': 100}), 
                    'start_date': forms.SelectDateWidget(),
                    'due_date': forms.SelectDateWidget(),
                    # 'resources': forms.FileInput()
                    # 'team': forms.CheckboxSelectMultiple(),
                }
 
# class TodoForm(forms.ModelForm):
    
#     text = forms.CharField()
#     # project = forms.ForeignKey()
#     name = forms.CharField()
#     create_date = forms.DateTimeField()
#     start_date = forms.DateTimeField()
#     due_date = forms.DateTimeField()
    
#     project_code = forms.CharField()
#     details = forms.TextInput()
#     class Meta:
#          model = Todo
#          fields = ['project', 'create_date']


class ProgressForm(forms.ModelForm):
    class Meta:
        model = Progress
        fields = ['project', 'text', 'name', 'start_date', 'due_date', 
                  'project_code', 'details']
        # labels = {'project': ''}
        # widgets = {'project': forms.Textarea(attrs={'col': 100})}


class DoneForm(forms.ModelForm):
    class Meta:
        model = Done
        fields = ['project', 'text', 'name', 'start_date', 'due_date', 
                  'project_code', 'details']
        # labels = {'project': ''}
        # widgets = {'project': forms.Textarea(attrs={'col': 100})}


class ResourceForm(forms.Form):
    resource = forms.FileField(label='resource', required=True, error_messages={'required':'Please select a file'})

class dragTodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['name', 'details']

# class dragProgressForm(forms.ModelForm):
#     class Meta:
#         model = Progress
#         fields = ['project', 'text', 'name', 'start_date', 'due_date', 
#                   'project_code', 'details']


class assign(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['employeeID', 'name', 'projects']

       

TEP-Final/todo_lists/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib import messages
from django.views.decorators.http import require_http_methods
# Create your views here.

# for forms
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse
from .models import Project, Todo, Progress, Done
from .forms import ProjectForm, TodoForm, ProgressForm, DoneForm, dragTodoForm
from .models import Team, wiki, resource
from .forms import ResourceForm
from django.db.models import Case, When, Count
from django.db.models import Q
# gantt chart
# import plotly.express as px
# import pandas as pd
import json
def index(request):
    # Todo list homepage
    return render(request, 'todo_lists/index.html')


def projects(request):
    # show all projects

    projects = Project.objects.order_by('project_code')
    context = {'projects': projects}
    return render(request, 'todo_lists/projects.html', context)


def project(request, project_id):
    
    project = Project.objects.get(id=project_id)
    
    todos = project.todo_set.filter(status='to_do').order_by('-project_code')
    progresses = project.todo_set.filter(status='in_progress').order_by('-project_code')
    dones = project.todo_set.filter(status='done').order_by('-project_code')
    context = {'project': project, 'todos': todos, 'progresses': progresses, 'dones': dones}
    return render(request, 'todo_lists/project.html', context)

# def task(request, todo_id):
    
#     todos = Todo.objects.get(id=todo_id)
    
#     project = todos.project
    
#     context = {'project': project, 'todos': todos}
#     return render(request, 'todo_lists/task_detail.html', context)



def teams(request):
    teams = Team.objects.order_by('name')
    context = {'teams':teams}
    return render(request, 'todo_lists/teams.html', context)

def team(request, team_id):
    
    team = Team.objects.get(id=team_id)
    
    todos = team.todo_set.filter(status='to_do').order_by('name')
    progresses = team.todo_set.filter(status='in_progress').order_by('name')
    dones = team.todo_set.filter(status='done').order_by('name')
    context = {'team': team, 'todos': todos, 'progresses': progresses, 'dones': dones}
    return render(request, 'todo_lists/team.html', context)

def project_progress(request, project_id):
    
    project = Project.objects.get(id=project_id)
    team = project.team_set.order_by('-project_code')
    context = {'project': project, 'team': team}
    return render(request, 'todo_lists/progress.html', context)

def assign(request):
    team = Team.objects.all()
    todos = Todo.objects.all().order_by('team')
    # progresses = team.todo_set.filter(status='in_progress')
    # dones = team.todo_set.filter(status='done')
    context = {'todos': todos, 'team': team}
    return render(request, 'todo_lists/assign.html', context)


def progress(request, pk):
    to = get_object_or_404(Todo, pk=pk)
    to.update_status()
    return redirect(reverse('todo_lists:project', kwargs={'project_id': to.project.pk}))


def drag(request, project_id):
    project = Project.objects.get(id=project_id)
    todo = Todo.objects.filter(status='to_do')
    progress = Todo.objects.filter(status='in_progress')
    done = Todo.objects.filter(status='done')
    context = {'todo', todo, 'progress', progress, 'done', done, 'project', project}
    return render(request, 'todo_lists/project.html', context)


def add_to_progress(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    # project = Project.objects.get(id=project_id)

    if request.method != 'POST':
        form = dragTodoForm()
    else:
        form = dragTodoForm(request.POST)
        if form.is_valid():  
            Todo.objects.filter(id=todo_id).update(status='in_progress')
            new_progress = form.save(commit=False)
            new_progress.project = project
            new_progress.save()
                   
        # progress = Todo.objects.filter(status='in_progress')
    context = {'form', form, 'todo', todo}
    return render(request, 'todo_lists/new_progress.html', context)


def add_to_done(request, todo_id, project_id):
    todo = Todo.objects.get(id=todo_id)
    project = Project.objects.get(id=project_id)

    if request.method != 'POST':
        form = dragTodoForm()
    else:
        form = dragTodoForm(request.POST)
        Todo.objects.filter(id=todo_id).update(status='done')
    context = {'form', form, 'todo', todo, 'project', project}
    return render(request, 'todo_lists/new_done.html', context)


# def drag_progress(request):
#     view = self.context['view']
#     todo_id = id
#     todo = Todo.objects.get(pk=todo_id)
#     copy_todo = todo.progress.all()

#     todo.id = None
#     todo.save()
#     for item in copy_todo:todo
#     item.save()
#     todo.progress.add(item)


def new_project(request):
    # add new project
    
    if request.method != 'POST':
        # if not submit then create a new form for user
        form = ProjectForm()
    else:
        form = ProjectForm(request.POST)
        if form.is_valid():
            
            form.save()
            return HttpResponseRedirect(reverse('todo_lists:projects'))
# team', 'name', 'due_date', 'project_code', 'details
    context = {'form': form}
    return render(request, 'todo_lists/new_project.html', context)


def new_todo(request, project_id):
    # add a to do task for a project
    project = Project.objects.get(id=project_id)
    # team = Team.objects.all().values
    team = Team.objects.all().values('name')
    if request.method != 'POST':
        form = TodoForm()
    else:
        form = TodoForm(data=request.POST)
        if form.is_valid():
            new_todo = form.save(commit=False)
            new_todo.project = project
            form.team = Team.objects.all().values('name')
            new_todo.save()
            return HttpResponseRedirect(reverse('todo_lists:project', args=[project_id]))
                                        
    context = {'project': project, 'form': form, 'team': team}
    return render(request, 'todo_lists/new_todo.html', context)


def new_progress(request, project_id):
    # add a in-progress for a project
    project = Project.objects.get(id=project_id)

    if request.method != 'POST':
        form = ProgressForm()
    else:
        form = ProgressForm(data=request.POST)
        if form.is_valid():
            new_progress = form.save(commit=False)
            new_progress.project = project
            new_progress.save()
            return HttpResponseRedirect(reverse('todo_lists:project', args=[project_id]))
                                        
    context = {'project': project, 'form': form}
    return render(request, 'todo_lists/new_progress.html', context)


def new_done(request, project_id):
    # add done tasks for a project
    project = Project.objects.get(id=project_id)
    
    if request.method != 'POST':
        form = DoneForm()
    else:
        form = DoneForm(data=request.POST)
        if form.is_valid():
            new_done = form.save(commit=False)
            new_done.project = project
            new_done.save()
            return HttpResponseRedirect(reverse('todo_lists:project', args=[project_id]))
                                        
    context = {'project': project, 'form': form}
    return render(request, 'todo_lists/new_done.html', context)


def edit_todo(request, todo_id):
    # edit current todo task

        todo = Todo.objects.get(id=todo_id)
    
        project = todo.project

        if request.method != 'POST':
            # first time filled with current content
            form = TodoForm(instance=todo)
        else:
            form = TodoForm(instance=todo, data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('todo_lists:project',
                                                    args=[project.id]))

        context = {'todo': todo, 'project': project, 'form': form}
        return render(request, 'todo_lists/edit_todo.html', context)


def edit_project(request, project_id):
    # edit current project

        project = Project.objects.get(id=project_id)
    

        if request.method != 'POST':
            # first time filled with current content
            form = ProjectForm(instance=project)
        else:
            form = ProjectForm(instance=project, data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('todo_lists:projects'))

        context = {'project': project, 'form': form}
        return render(request, 'todo_lists/edit_project.html', context)


     
def delete_todo(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    
    if request.method == "POST":
        todo.delete()
        return HttpResponseRedirect(reverse('todo_lists:projects'))

    context = {'todo': todo}
    return render(request, 'todo_lists/delete.html', context)


def delete_project(request, project_id):
    project = Project.objects.get(id=project_id)
    if request.method == "POST":
        project.delete()
        return HttpResponseRedirect(reverse('todo_lists:projects'))

    context = {'project': project}
    return render(request, 'todo_lists/delete_project.html', context)


def edit_progress(request, progress_id):
    # edit current in-progress task
    progress = Progress.objects.get(id=progress_id)
    project = progress.project

    if request.method != 'POST':
        # first time filled with current content
        form = ProgressForm(instance=progress)
    else:
        form = ProgressForm(instance=progress, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('todo_lists:project',
                                                args=[project.id]))

    context = {'progress': progress, 'project': project, 'form': form}

TEP-Final/todo_lists/templates/todo_lists/delete.html
<!DOCTYPE html>
{% extends "todo_lists/base.html" %}
<!-- {% block title %}Delete Page{% endblock %} -->

{% block delete %}
{% load static %}
<div class="delete_distance">
<div class="row my-4">
    <div class="col-md-6 offset-md-3">
        <div class="border p-3 bg-white">
            <h3>Delete This Task:</h3>
            <hr>
            <form action="{% url 'todo_lists:delete_todo' todo.id %}" method="post">
                <div class="alert alert-danger">
                    <h4>Are you sure, you want to delete "{{ todo.name }}"?</h4>
                </div>
                {% csrf_token %}
                
                
                <input class="btn btn-danger btn-sm" type="submit" value="Confirm">
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}

TEP-Final/todo_lists/templates/todo_lists/project.html
<!doctype html>
{% extends "todo_lists/base.html" %}
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-main-function-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
<!-- add list button -->
{% block todo %}

	<div class="modal" id="todo_form">
	  <div class="header">
	    <div class="title">Add New List</div>
	    <button id= "titleclosebtn" class="btn close-modal">&times;</button>
	  </div>
	  <div class="body">
	    <input type="text" id="todo_input1" placeholder="Write a new task name" required/>
	    <input type="text" id="todo_input2" placeholder="Write the task description"/>
	    <input type="submit" value="Add" id="todo_submit" />
	  </div>
	</div>
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-to-do-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
<!-- todo list -->

{% load static %}

  <!-- <div id="progress_container">

  </div> -->
  <!-- <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
    <div class="col">
      <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" > -->



          
        <!-- <h2 class="pb-2 border-bottom" style="text-align: center; float: t;">Projects
          <a href="{% url 'todo_lists:new_project'%}" class="btn btn-outline-warning btn btn-primary" style="float:right;color: white;">Add new project      <img src="{% static '../static/img/addd.png'%}" alt="addpic" width="25" height="25"></a>
        </h2> -->
      
  <section class="inline"  style="display: table; ">
    <div class="toplist">
      <div id="addDiv">
        To-do list        
        <a href="{% url 'todo_lists:new_todo' project.id %}" class="add_task" style="float: right;">

          <img src="{% static '../static/img/addd.png'%}"  alt="add_task_pic" width="25" height="25"></a>
      </div>       
    </div>
    
    <div class="innerbox">
      {% for todo in todos %}
      <div class="inner" draggable="true" style="display: table-row-group;">
        <div class="row">              
          <div >
            <a href="{% url 'todo_lists:edit_todo' todo.id %}" style="float: right;" >
              <img src="{% static '../static/img/edit.png'%}"  alt="editpic" width="12" height="15"></a>

            <a href="{% url 'todo_lists:delete_todo' todo.id %}" style="float: right;">
              <img src="{% static '../static/img/delete_project.png'%}"  alt="deletepic" width="12" height="15"></a>
              
            <p class="h3">Task Name:<span class="h3" style="font-family: Yanone Kaffeesatz">{{ todo.name }}</sp></p>    
          </div>
          <p  class="h3">Details:          <span  class="h3" style="font-family: Yanone Kaffeesatz">{{ todo.details }}</span>
          </p>            
          <p  class="h3">Due Date:          <span  class="h3" style="font-family: Yanone Kaffeesatz">{{ todo.due_date }}</span>
          </p>
          <p  class="h3">Team Member:          <span   class="h3" style="font-family: Yanone Kaffeesatz">{{ todo.team.name }}</span>
          </p>
          <form method="post" action="{% url 'todo_lists:todoprogress' todo.pk %}" style="display: table-row;">
            {% csrf_token %}
            <button type="submit" class="btn btn btn-outline-success btn-sm" style="float: right;">Doing</button>
          </form>
        </div>

      </div> 
      {% empty %}
      <li>                                           </li>
    {% endfor %} 
    </div>            
  </section>

  <section class="inline"  style="display: table;">
    <div class="toplist" >
      <div id="addDiv">
        In progress   
        <span id="progress_button" >
          <a href="{% url 'todo_lists:visualisation' project.id %}" class="btn btn-warning btn-block view_progress2" >Click Here to View Project {{ project.project_code }}'s Progress</a>
        </span>    
        <!-- <a href="{% url 'todo_lists:new_todo' project.id %}" class="add_task" style="float: right;">

          <img src="{% static '../static/img/addd.png'%}"  alt="add_task_pic" width="25" height="25"></a> -->
      </div>       
    </div>
    
    <div class="innerbox">
      {% for progress in progresses %}
      <div class="inner" draggable="true"  style="display: table-row-group;">
        <div class="row">              
          <div >
            <a href="{% url 'todo_lists:edit_todo' progress.pk %}" style="float: right;">
              <img src="{% static '../static/img/edit.png'%}"  alt="editpic" width="12" height="15"></a>

            <a href="{% url 'todo_lists:delete_todo' progress.pk %}" style="float: right;">
              <img src="{% static '../static/img/delete_project.png'%}"  alt="deletepic" width="12" height="15"></a>
              
            <p class="h3">Task Name:            <span class="h3" style="font-family: Yanone Kaffeesatz">{{ progress.name }}</span>
            </p>    
          </div>
          <p  class="h3">Details:<span  class="h3" style="font-family: Yanone Kaffeesatz">{{ progress.details }}</span></p>            
          
          <p  class="h3">Due Date:          <span  class="h3" style="font-family: Yanone Kaffeesatz">{{ progress.due_date }}</span>
          </p>
          <p  class="h3">Team Member:          <span   class="h3" style="font-family: Yanone Kaffeesatz">{{ progress.team.name }}</span>
          </p>
          <form method="post" action="{% url 'todo_lists:todoprogress' progress.pk %}" style="display: table-row;">
            {% csrf_token %}
            <button type="submit" class="btn btn btn-outline-success btn-sm" style="float: right;">Done</button>
          </form>
        </div>

      </div> 
      {% empty %}
      <li>                                      </li>
    {% endfor %} 
    </div>            
  </section>

  <section class="inline"  style="display: table; overflow: auto;">
    <div class="toplist">
      <div id="addDiv">
        Done      
        <!-- <a href="{% url 'todo_lists:new_todo' project.id %}" class="add_task" style="float: right;">
  
          <img src="{% static '../static/img/addd.png'%}"  alt="add_task_pic" width="25" height="25"></a> -->
      </div>       
    </div>
    <div class="innerbox">
 
      {% for done in dones %}
      <div class="inner" draggable="true"  style="display: table-row-group;">
 
        <div class="row">              
          <div >
            <a href="{% url 'todo_lists:edit_todo' done.pk %}" style="float: right;">
              <img src="{% static '../static/img/edit.png'%}"  alt="editpic" width="12" height="15"></a>
  
            <a href="{% url 'todo_lists:delete_todo' done.pk %}" style="float: right;">
              <img src="{% static '../static/img/delete_project.png'%}"  alt="deletepic" width="12" height="15"></a>
              
            <p class="h3">Task Name:            <span class="h3" style="font-family: Yanone Kaffeesatz">{{ done.name }}</span>
            </p>    
            <p  class="h3">Details:            <span  class="h3" style="font-family: Yanone Kaffeesatz">{{ done.details }}</span>
            </p>            
            <p  class="h3">Due Date:            <span  class="h3" style="font-family: Yanone Kaffeesatz">{{ done.due_date }}</span>
            </p>
            <p  class="h3">Team Member:            <span  class="h3" style="font-family: Yanone Kaffeesatz">{{ done.team.name }}</span>
            </p>
          </div>

  
        </div>
        
 
      </div> 
      {% empty %}
        <li>No task has been done.</li>
      {% endfor %}
    </div>            
  </section>    
 <!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-in-progress-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --> 
      
      <!-- <section class="inline">
        <div class="toplist">
          <div>In progress</div>
        </div>
        <div class="innerbox">
          {% for progress in progresses %}
          <div class="inner" draggable="true">
            <div class="row">
              <div class="col-sm">
                <p>Task:</p>
              </div>
              <div class="col-sm">
                <p style="font-family: Yanone Kaffeesatz">{{ progress.name }}</p>
              </div>
              <div class="col-sm">
                <p><a href="{% url 'todo_lists:delete_todo' progress.pk %}">
                  <img src="{% static '../static/img/delete.png'%}"  alt="deletepic" width="12" height="15"></a></p>
              </div>
            </div>
            
                <p>Details:</p>
              
            
                <p style="font-family: Yanone Kaffeesatz">{{ progress.details }}</p>
                <p>Due:{{ todo_due_date }}</p>
            <div class="container">
              <div class="row">
                <div class="col-sm">
                    <p><a href="{% url 'todo_lists:edit_todo' progress.pk %}"><img src="{% static '../static/img/edit2.png'%}"  alt="editpic" width="12" height="15"></a></p>
                  </div>
                  <div class="col-sm">
                  
                </div>
                  <div class="col-sm">
                    <form method="post" action="{% url 'todo_lists:todoprogress' progress.pk %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-success btn-sm">Done</button>
                    </form>
                  </div>
                  <div class="col-sm">
                    <p class="teamname">{{ progress.team.name }}</p>
                  </div>     
                </div>
            </div> 
          </div>
          {% empty %}
            <li>No task is now in progress.</li>
          {% endfor %}
        </div>

      </section> -->
    
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-done-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
 


      <!-- <section class="inline">
        <div class="toplist">
          <div>Done</div>
        </div>
        <div class="innerbox">
          {% for done in dones %}
          <div class="inner" draggable="true">
            <div class="row">
              <div class="col-sm">
                <p>Task:</p>
              </div>
              <div class="col-sm">
                 <p style="font-family: Yanone Kaffeesatz">{{ done.name }}</p>
              </div>
              <div class="col-sm">
                <p><a href="{% url 'todo_lists:delete_todo' done.pk %}">
                  <img src="{% static '../static/img/delete.png'%}"  alt="deletepic" width="12" height="15"></a></p>
              </div>
            </div>
            
                <p>details:</p>
              
              
                <p style="font-family: Yanone Kaffeesatz">{{ done.details }}</p>
                <p>Due:{{ todo_due_date }}</p>
            <div class="container">
              <div class="row">
                <div class="col-sm">
                    <p><a href="{% url 'todo_lists:edit_todo' done.pk %}"><img src="{% static '../static/img/edit2.png'%}"  alt="editpic" width="12" height="15"></a></p>
                </div>
                <div class="col-sm">
                  
                </div>
                <div class="col-sm">
                    
                </div>
                <div class="col-sm">
                  <p class="teamname">{{ done.team.name }}</p>
                </div>
            </div>

          </div>
          
        </div>
          {% empty %}
            <li>No task is has been done.</li>
          {% endfor %}
          
        </div>
      </section> -->

  	{% block task %} {% endblock %}

 <footer>
 </footer>
 <!-- <div id="overlay"></div> -->
 {% endblock %}